# name: Test

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:

#     - name: Set up Go 1.x
#       uses: actions/setup-go@v2
#       with:
#         go-version: ^1.16
#       id: go

#     - name: Check out code into the Go module directory
#       uses: actions/checkout@v3

#     - name: Get dependencies
#       run: |
#         go mod download

#     - name: Test
#       env:
#         CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
#         CONTENTFUL_ORGANIZATION_ID: ${{ secrets.CONTENTFUL_ORGANIZATION_ID }}
#         SPACE_ID: ${{ secrets.SPACE_ID }}
#         ENV_ID: ${{ secrets.ENV_ID }}
#       run: |
#         make testacc

#     - name: Convert coverage to lcov
#       uses: jandelgado/gcov2lcov-action@v1.0.0
#       if: github.ref == 'refs/heads/main'
#       with:
#         infile: cover.out
#         outfile: cover.lcov

#     - name: Coveralls
#       uses: coverallsapp/github-action@master
#       if: github.ref == 'refs/heads/main'
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         path-to-lcov: cover.lcov
